excludes:
  folders:
    [target,node_modules,bower_components,automation,META-INF]
includes:
  packagejson: [version]
  bower:
    defaults:
      - version
      - ct-common-ui
      - ct-product-manager-ui
    endings:
      js:
        - dist/release/ct-common-ui

