= Release Management Tool for Maven/node.js projects

== Introduction

The application finds all pom.xml files as well as all package.json and bower.json
recursively and updates them to a given version according to a given configuration.
For pom files it also adds -SNAPSHOT in the version (if applicable).

== Usage

. Copy the maven-produced jar in the root folder of the project you want to release.
. Create a configuration.yml file to configure what needs to be updated
in package and bower files (check example: link:configuration.yml[configuration.yml])
. For console application:
.. run maven install with default profile to create a jar
.. run jar with `java -jar jar-name.jar`
... run `bump [action]` where action is `major`, `minor`, `build`, `prod`, `snapshot` or
... run `release [version]` where version is of the form `ddd.ddd.ddd[-SNAPSHOT]`
. For Java FX application:
.. run `maven install` with profile `java-fx` to create a self-executing jar
.. double click the jar
.. enter commands as above in the UI

Example commands:

 $ bump minor

 $ release 1.0.1-SNAPSHOT

 $ release 1.0.2

NOTE: The `prod` action removes -SNAPSHOT from version (in pom files).
The `snapshot` action adds -SNAPSHOT in version (in pom files),

== Development

For the *console application*, to run this project from inside an IDE a VM parameter is needed in run configuration:

 -Djline.terminal=jline.UnsupportedTerminal

This is required if you want to capture console input inside the IDE.

To be able to compile the project the Lombok plugin is needed